WITH SALE AS (
    SELECT U.USER_ID, 
        YEAR(O.SALES_DATE) AS "YEAR",
        MONTH(O.SALES_DATE) AS "MONTH"
    FROM USER_INFO AS U
    LEFT JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
    WHERE YEAR(U.JOINED) = 2021
)


SELECT YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS "PUCHASED_USERS",
    ROUND(
        COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM SALE)
        , 1
    ) AS "PUCHASED_RATIO"
FROM SALE
WHERE YEAR AND MONTH IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

