
SELECT DATE_FORMAT(tbl.SALES_DATE, "%Y-%m-%d") AS "SALES_DATE", 
    tbl.PRODUCT_ID, 
    tbl.USER_ID, 
    tbl.SALES_AMOUNT
FROM (
    SELECT *
    FROM ONLINE_SALE
    UNION ALL
    SELECT OFFLINE_SALE_ID, NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE
) AS tbl
WHERE DATE_FORMAT(tbl.SALES_DATE, "%Y-%m") = "2022-03"
ORDER BY tbl.SALES_DATE, tbl.PRODUCT_ID, tbl.USER_ID;