WITH RENTAL_PLAN AS (
    SELECT DURATION_TYPE, 
        1 - DISCOUNT_RATE/100 AS "DISCOUNT_RATE"
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = "트럭"
)


SELECT TBL.HISTORY_ID,
FLOOR(
    CASE
        WHEN TBL.DURATION < 7 THEN DAILY_FEE * DURATION
        WHEN TBL.DURATION < 30 THEN DAILY_FEE * DURATION * (
            SELECT DISCOUNT_RATE
            FROM RENTAL_PLAN
            WHERE DURATION_TYPE = "7일 이상"
        )
        WHEN TBL.DURATION < 90 THEN DAILY_FEE * DURATION * (
            SELECT DISCOUNT_RATE
            FROM RENTAL_PLAN
            WHERE DURATION_TYPE = "30일 이상"
        )
        ELSE DAILY_FEE * DURATION * (
            SELECT DISCOUNT_RATE
            FROM RENTAL_PLAN
            WHERE DURATION_TYPE = "90일 이상"
        )
    END
) AS "FEE"
FROM(
    SELECT HISTORY_ID, 
        DAILY_FEE, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS "DURATION"
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = "트럭"
) AS TBL
ORDER BY FEE DESC, HISTORY_ID DESC;


