SELECT A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(B.PRICE * S.SALES) AS "TOTAL_SALES"
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS S
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") = "2022-01"
    AND B.AUTHOR_ID = A.AUTHOR_ID
    AND B.BOOK_ID = S.BOOK_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;
