SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS 'SALES'
FROM OFFLINE_SALE AS O
    JOIN PRODUCT AS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE