SET @START = -1;

SELECT H.HOUR, COUNT(ANIMAL_ID) AS "COUNT"
FROM ANIMAL_OUTS AS O
RIGHT JOIN (
    SELECT @START := @START + 1 AS "HOUR"
    FROM ANIMAL_OUTS
    LIMIT 24
) AS H
ON HOUR(O.DATETIME) = H.HOUR
GROUP BY H.HOUR;


